run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - structcheck
    - ineffassign
    - deadcode
    - gocritic

issues:
  exclude-use-default: false
  max-same-issues: 5
  max-issues-per-linter: 10
