FROM golang:1.24-bullseye AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    librdkafka-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /integrationtesting

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/scripts/install_dependencies.sh cmd/scripts/
RUN chmod +x cmd/scripts/install_dependencies.sh && \
    sh cmd/scripts/install_dependencies.sh

COPY testapp ./testapp

WORKDIR /integrationtesting/testapp
RUN go mod tidy
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go test -c -o /integrationtesting/integ .

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    librdkafka1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /integrationtesting
COPY --from=builder /integrationtesting/integ .

CMD ["./integ", "-test.v"]
