version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"        # expose app HTTP server on host:8080
    depends_on:
      - db
      - kafka
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      JWT_SECRET: w4X8bY9s4fJ7nHxPlA+2Fv7Yq8RmQO3SZj8Phq+k6Xo=
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: companiesdb
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: companiesdb
      DB_USER: root
      DB_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER: kafka:9092
    depends_on:
      - zookeeper
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network: