// Code generated by MockGen. DO NOT EDIT.
// Source: createRecordHandler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	database "companies/cmd/internal/database"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockcreateRecordDB is a mock of createRecordDB interface.
type MockcreateRecordDB struct {
	ctrl     *gomock.Controller
	recorder *MockcreateRecordDBMockRecorder
}

// MockcreateRecordDBMockRecorder is the mock recorder for MockcreateRecordDB.
type MockcreateRecordDBMockRecorder struct {
	mock *MockcreateRecordDB
}

// NewMockcreateRecordDB creates a new mock instance.
func NewMockcreateRecordDB(ctrl *gomock.Controller) *MockcreateRecordDB {
	mock := &MockcreateRecordDB{ctrl: ctrl}
	mock.recorder = &MockcreateRecordDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateRecordDB) EXPECT() *MockcreateRecordDBMockRecorder {
	return m.recorder
}

// CreateRecord mocks base method.
func (m *MockcreateRecordDB) CreateRecord(arg0 database.CompanyInfo) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecord", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecord indicates an expected call of CreateRecord.
func (mr *MockcreateRecordDBMockRecorder) CreateRecord(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecord", reflect.TypeOf((*MockcreateRecordDB)(nil).CreateRecord), arg0)
}

// IsRecordExists mocks base method.
func (m *MockcreateRecordDB) IsRecordExists(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRecordExists", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRecordExists indicates an expected call of IsRecordExists.
func (mr *MockcreateRecordDBMockRecorder) IsRecordExists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRecordExists", reflect.TypeOf((*MockcreateRecordDB)(nil).IsRecordExists), arg0)
}
