db:
  host: db
  port: "3306"
  name: companiesdb
  user: root
  password: password

kafka:
  broker: kafka:9092

http:
  addr: "0.0.0.0"
  port: "8080"
  read_timeout_seconds: 15
  write_timeout_seconds: 15