global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'golang-app'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
